name = "SynapseUploadUtils"
uuid = "652ca483-535c-499c-9761-633da526f0bd"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
